### ISSUE TITLE
warning about SwiftLint

### ISSUE THREAD

**Issue by diuming** [CharlesJS/CSAuthSample#2]
macOS 10.15.4
Xcode 11.4

I can't build it on my Mac.
Could you give me some advice?
Why Do I need to use SwiftLint?
thanks

warnings and errors
---
```
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by diuming** [comment]
abandonment of use

**Comment by CharlesJS** [comment]
Sorry for not seeing this earlier. SwiftLint is mostly for my benefit in cleaning up the code for open-source consumption; the script in question was copy-and-pasted from the SwiftLint docs. Since it's just a warning, I'm not sure why that warning should prevent compilation, but as it's unnecessary, I've removed it. Does it build for you now?
