### ISSUE TITLE
Unable to Compile; Related to Missing Config Variables, Appears GlobalScriptSetup.swift Currently Required But Never Runs

### ISSUE THREAD

**Issue by insanj** [CharlesJS/CSAuthSample#3]
👋 Hello! Super useful project here. I have an issue/question about running this on the latest macOS.

As of today, it seems it is impossible to compile this project without the `CSAuthSample-Example.xcconfig` file being completely filled out. Luckily for us, `GlobalSetupScript.swift` seems designed to do this.

⚠️ Here's my problem: the following file, [Common/Build Scripts/GlobalSetupScript.swift](https://github.com/CharlesJS/CSAuthSample/blob/master/CSAuthSample%20Example%20App/Common/Build%20Scripts/GlobalSetupScript.swift), which is responsible for generating the required [CSAuthSample-Example.xcconfig](https://github.com/CharlesJS/CSAuthSample/blob/master/CSAuthSample%20Example%20App/Common/Config/CSAuthSample-Example.xcconfig) file, appears to never be executed at any time. So, when I try to build the project, it fails with:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file SetupHelperPlists/SetupHelperPlists.swift, line 14
```
<img width="267" alt="Screen Shot 2021-03-12 at 11 37 28 PM" src="https://user-images.githubusercontent.com/951011/111019241-e9bb6f80-838b-11eb-93dd-1c38eb3f509c.png">

Unfortunately, `GlobalSetupScript.swift` appears to not be reference by any Build Phase or script event. As such, this `.xcconfig` file is never filled out on time and this project cannot be compiled.

If I manually supply the required keys to the `.xcconfig`, I can get around this error, but this is particularly unenjoyable to do for the relatively complex `CS_REQUIREMENT` value.

By default, this `CSAuthSample-Example.xcconfig` looks like this:
```
CURRENT_PROJECT_VERSION = 1
```

And if we change it to this, the project no longer fails to compile:
```
APP_BUNDLE_ID = "com.charlessoft.CSAuthSample-Example"
XPC_SERVICE_ID = "com.charlessoft.CSAuthSample-Example.XPCService"
HELPER_ID = "com.charlessoft.CSAuthSample-Example.helper"
CS_REQUIREMENT = ""
```

🤔  Is there a chance this is something that can be resolved, or something I overlooked, in the project setup? Besides that, very much appreciate this tool and I can't wait to keep using it.

**Comment by CharlesJS** [comment]
Hello, and thanks for your interest in this project!

The `GlobalSetupScript.swift` script, along with some other things, is run from a pre-build action on the `Example App` scheme. Unfortunately, it looks like on the latest Xcode, it's been crashing (and not reported by Xcode's UI; unfortunately, the failure to report errors in pre-build actionns is a long-standing issue in Xcode that has yet to be resolved, but this example app works around that by logging output from the action to a file in `/tmp`).

As to what went wrong, it looks like at some point, Xcode moved the point at which it creates the `TEMP_DIR` directory to a later point in the build process, causing it not to exist at the point that the scripts run, and consequently for the file writes to fail. It looks like `DERIVED_FILE_DIR` is written early enough, and in hindsight, that's probably a more proper place to write these files anyway. I've pushed an update that should hopefully build on your machine now; please let me know if it doesn't.

Again, thanks for reporting this issue. The example app is the part of this project that doesn't get utilized by my everyday build process, so it really helps me out to be informed when issues like this crop up.

**Comment by insanj** [comment]
@CharlesJS Thanks so much! Excellent work, the latest commit build and runs on my machine with the latest Xcode.

I do have one, perhaps unrelated question: does the Helper Tool re-install every time you click "Say Hello"? I've been trying to learn up on macOS authentication more, and I noticed that in `HelperClient`, the uninstall method is called in the body of the install method. I can't quite tell if the Helper Tool is re-authenticating every time you click for demonstration, or by necessity.

Again, sorry if I'm barking up the wrong tree here, but is the intended use of these authentication tools to prompt for password to run a one-time script, and then never be ran again? I was hoping, instead, to use this as a reference for building a tool that you authorize once on install, then persists those authentication credentials across restarts. So you can run the same script multiple times.

Perhaps I've been misguided in thinking that this form of macOS authentication is meant for that, or perhaps I've just been naive. My goal is primarily to ask for permission to run a script once, then run it when a user clicks a button without having to ask for pass every time (or having to cache their password using some insecure means). I _do_ think this library can help with that, and perhaps is designed for that, but I'm having a hard time grasping how to accomplish it.

Thanks so much either way for making this invaluable resource! 🍻

**Comment by insanj** [comment]
Also, not sure if this is something on my end with the bundle identifier, but I had some issues Archiving so I could test running on launch from `/Applications`:

<img width="1135" alt="Screen Shot 2021-03-17 at 9 39 14 PM" src="https://user-images.githubusercontent.com/951011/111560631-3e366480-8769-11eb-972c-1e85760dd56c.png">

**Comment by CharlesJS** [comment]
Sorry about the archiving issue; turns out there was one more instance of `TEMP_DIR` that I missed last time. It should work now.

> @CharlesJS Thanks so much! Excellent work, the latest commit build and runs on my machine with the latest Xcode.
> 
> I do have one, perhaps unrelated question: does the Helper Tool re-install every time you click "Say Hello"?

The helper tool should reinstall itself the first time you click the button, and you will be prompted for your admin password for the installation ("Example XPC Service is trying to install a new helper tool"). Then, it you'll get the prompt to access the tool's "Say-Hello" command, because the tool is configured to require admin authentication (CSAuthSample Example App would like to say hello), which I think is a sensible default.

On subsequent launches of the app, the helper will already be installed, and will _not_ need reinstallation, so you'll only get the one prompt that the "Say-Hello" command is asking for.

However, if you rebuild the project, it will then require installation of the helper again. This is because the project is set to auto-increment the build number, so the app's build number will now be ahead of the helper tool's, indicating the the tool is out of date and needs updating.

> I've been trying to learn up on macOS authentication more, and I noticed that in `HelperClient`, the uninstall method is called in the body of the install method. I can't quite tell if the Helper Tool is re-authenticating every time you click for demonstration, or by necessity.

The reason the uninstall method is called in the install method is because when you are installing a new version of the helper tool, you will want to remove any older versions that are already installed first.

> Again, sorry if I'm barking up the wrong tree here, but is the intended use of these authentication tools to prompt for password to run a one-time script, and then never be ran again? I was hoping, instead, to use this as a reference for building a tool that you authorize once on install, then persists those authentication credentials across restarts. So you can run the same script multiple times.

The purpose of authentication is to run a helper tool as root, to do the sort of things you would need `sudo` for at the command line. Whether you run that tool again is up to you.

> Perhaps I've been misguided in thinking that this form of macOS authentication is meant for that, or perhaps I've just been naive. My goal is primarily to ask for permission to run a script once, then run it when a user clicks a button without having to ask for pass every time (or having to cache their password using some insecure means). I _do_ think this library can help with that, and perhaps is designed for that, but I'm having a hard time grasping how to accomplish it.

What level of authorization the commands require is set in the command set, which in the example app is [here](https://github.com/CharlesJS/CSAuthSample/blob/2c0e9a0907dfdeab7806895776a65ec8dba7d471/CSAuthSample%20Example%20App/Common/ExampleCommandSet.swift#L23). You can set this to any of the [policy database constants](https://developer.apple.com/documentation/security/authorization_services/policy_database_constants), but keep in mind that you can create some serious security issues this way if you're not careful, since a helper tool that doesn't require authentication is similar in effect to a script that has its setuid bit set. Once you've installed the tool, another app whose developer has figured out your command set could send messages to it, so you need to make sure the functionality of your tool is as focused as possible, to limit the possibility that a malicious app could use your tool for nefarious purposes. You need to be extremely careful whenever you're escalating privileges; otherwise, you could easily open up a rootkit on your users' machines. For that reason, I generally prefer just to ask for an admin password each time, the way `sudo` would.

> Thanks so much either way for making this invaluable resource! 🍻

You're welcome.
